CREATE OR REPLACE PACKAGE BODY emp_pkg AS
	PROCEDURE HIREEMP
	(
		a EMPLOYEE.EMPID%TYPE ,
		b EMPLOYEE.EMPNAME%TYPE ,
		c EMPLOYEE.JOB%TYPE ,
		d EMPLOYEE.MANAGER%TYPE ,
		e EMPLOYEE.DEPTNO%TYPE ,
		f EMPLOYEE.HIREDATE%TYPE ,
		g EMPLOYEE.SALARY%TYPE ,
		h EMPLOYEE.COMISSION%TYPE
	)
	IS
	BEGIN
		INSERT INTO EMPLOYEE VALUES(a , b , c , d , e , f , g , h);
	END HIREEMP;
		
	FUNCTION EMPUPDATE(n  IN EMPLOYEE.EMPNAME%TYPE)
	RETURN EMPLOYEE.COMISSION%TYPE
	IS
		newcomm EMPLOYEE.COMISSION%TYPE;
	BEGIN
		UPDATE EMPLOYEE SET COMISSION=COMISSION+(0.05*COMISSION) WHERE EMPNAME=n;
		SELECT COMISSION INTO newcomm FROM EMPLOYEE WHERE EMPNAME=n;
		RETURN newcomm;
	END EMPUPDATE;
END emp_pkg;

