CREATE TRIGGER UPD 
AFTER INSERT ON TRANSACTION
FOR EACH ROW
BEGIN
	IF :NEW.OPERATION ='w' then
			update MASTER set MASTER.BALANCE=MASTER.BALANCE-:NEW.TAMOUNT where ACCNO=:NEW.TACCNO;
	ELSE
			update MASTER set MASTER.BALANCE=MASTER.BALANCE+:NEW.TAMOUNT where ACCNO=:NEW.TACCNO;
	end IF;
END;